### PR TITLE
Fix race: pool kept connections after closure

### LINKED ISSUE #529: data race on bolt connection shutdown
- Driver version: 5.12.0

**Steps to reproduce**

- Expected behavior
driver does not trigger data races when running under `go test -race`

- Actual behavior

we see regular (>50% of `go test -race` runs) data races in the neo4j driver connection shutdown code:

```
=== RUN   TestStartCleanup/with_zero_duration
==================
WARNING: DATA RACE
Read at 0x00c000602680 by goroutine 1848:
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).Close()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:928 +0xe6
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*server).removeIdleOlderThan.func1()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/server.go:192 +0x61

Previous write at 0x00c000602680 by goroutine 1847:
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).setError()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:205 +0x1ba
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).onIoError()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:1138 +0xc4
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).onIoError-fm()
      <autogenerated>:1 +0x64
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*outgoing).send()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/outgoing.go:263 +0x99
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*messageQueue).send()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/message_queue.go:134 +0x1b4
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).Close()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:931 +0x13c
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.closeAndEmptyConnections.func1()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/server.go:222 +0x61

Goroutine 1848 (running) created at:
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*server).removeIdleOlderThan()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/server.go:192 +0x464
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*Pool).removeIdleOlderThanOnServer()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/pool.go:385 +0x157
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*Pool).Return()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/pool.go:411 +0x395
  github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).Run()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/session_with_context.go:624 +0xca3
  github.com/overmindtech/revlink/revlink.DeleteExpiredEdges()
      /home/runner/work/revlink/revlink/revlink/cleanup.go:152 +0x2f7
  github.com/overmindtech/revlink/revlink.cleanupAll()
      /home/runner/work/revlink/revlink/revlink/cleanup.go:247 +0x479
  github.com/overmindtech/revlink/revlink.StartCleanup.func1()
      /home/runner/work/revlink/revlink/revlink/cleanup.go:221 +0x1b2

Goroutine 1847 (finished) created at:
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.closeAndEmptyConnections()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/server.go:222 +0x1eb
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*server).startClosing()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/server.go:216 +0x32d
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*Pool).deactivate()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/pool.go:505 +0x298
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/pool.(*Pool).OnIoError()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/pool/pool.go:491 +0x5d
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).onIoError()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:1136 +0xa7
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).onIoError-fm()
      <autogenerated>:1 +0x64
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*outgoing).send()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/outgoing.go:263 +0x99
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*messageQueue).send()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/message_queue.go:134 +0x573
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).run()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:568 +0x4c5
  github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/bolt.(*bolt5).Run()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/internal/bolt/bolt5.go:621 +0x2b4
  github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).Run()
      /home/runner/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.12.0/neo4j/session_with_context.go:604 +0x5b3
  github.com/overmindtech/revlink/revlink.DeleteExpiredEdges()
      /home/runner/work/revlink/revlink/revlink/cleanup.go:152 +0x2f7
  github.com/overmindtech/revlink/revlink.cleanupAll()
      /home/runner/work/revlink/revlink/revlink/cleanup.go:247 +0x479
  github.com/overmindtech/revlink/revlink.StartCleanup.func1()
      /home/runner/work/revlink/revlink/revlink/cleanup.go:221 +0x1b2
==================
```

The issue goes away when downgrading to v5.11.0.

### PR DESCRIPTION
**Pull request by robsdedude**
Likely fixes #529

### CODE REVIEW

File: neo4j/internal/pool/server.go [hunk 1]
```diff
@@ -197,9 +197,9 @@ func (s *server) removeIdleOlderThan(ctx context.Context, now time.Time, maxAge
 }
 
 func (s *server) closeAll(ctx context.Context) {
-	closeAndEmptyConnections(ctx, s.idle)
+	closeAndEmptyConnections(ctx, &s.idle)
```
Comment (fbiville) [inline neo4j/internal/pool/server.go:200]: ouch, thanks for spotting and fixing this

**Review by fbiville — APPROVED** [review]
